# Generated by Django 3.2.7 on 2021-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verf', models.CharField(max_length=100, verbose_name='Verificacion:')),
                ('contador', models.IntegerField(verbose_name='Repeticion por turno:')),
            ],
            options={
                'verbose_name': 'Verificacion',
                'verbose_name_plural': 'Verificaciones',
            },
        ),
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verf', models.CharField(max_length=100, verbose_name='Verificacion:')),
                ('contador', models.IntegerField(verbose_name='Repeticion por turno:')),
            ],
            options={
                'verbose_name': 'Verificacion',
                'verbose_name_plural': 'Verificaciones',
            },
        ),
    ]
