# Generated by Django 3.2.8 on 2021-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aprobar_piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(editable=False, max_length=100, verbose_name='Maquina')),
                ('area', models.CharField(editable=False, max_length=100, verbose_name='Area')),
                ('recibida', models.BooleanField(editable=False, verbose_name='Recibida')),
                ('aprobada', models.BooleanField(editable=False, verbose_name='Aprobada')),
                ('rechazada', models.BooleanField(editable=False, verbose_name='Rechazada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cambio:')),
            ],
            options={
                'verbose_name': 'Aprobar',
                'verbose_name_plural': 'Aprobar',
            },
        ),
    ]
