# Generated by Django 3.2.7 on 2021-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_estados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='colorfondo',
            field=models.CharField(default='white', max_length=100, verbose_name='Color de fondo'),
        ),
        migrations.AddField(
            model_name='estados',
            name='colorletra',
            field=models.CharField(default='black', max_length=100, verbose_name='Color de letra'),
        ),
    ]
