# Generated by Django 3.2.7 on 2021-10-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_estados', '0002_auto_20211006_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='nivel',
            field=models.IntegerField(default=3, verbose_name='Nivel'),
        ),
    ]
