# Generated by Django 3.2.7 on 2021-10-05 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(editable=False, max_length=100, verbose_name='maquina')),
                ('area', models.CharField(editable=False, max_length=10, verbose_name='área')),
                ('estado', models.CharField(editable=False, max_length=100, verbose_name='estado')),
                ('departamento', models.CharField(editable=False, max_length=100, verbose_name='área')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado:')),
                ('active', models.BooleanField(editable=False, verbose_name='¿Activa?')),
                ('cambio', models.DateTimeField(auto_now=True, verbose_name='Cambio:')),
                ('duracion', models.DurationField()),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
