# Generated by Django 3.2.7 on 2021-10-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('F_registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='duracion',
        ),
    ]
