# Generated by Django 3.2.7 on 2021-10-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F_registros', '0002_remove_registros_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='usuario',
            field=models.IntegerField(editable=False, verbose_name='Usuario'),
        ),
    ]
