# Generated by Django 3.2.7 on 2021-10-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F_registros', '0003_alter_registros_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='comment',
            field=models.CharField(editable=False, max_length=200, null=True, verbose_name='comentario'),
        ),
    ]
