# Generated by Django 3.2.8 on 2021-11-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F_registros', '0004_registros_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='id_estado',
            field=models.IntegerField(default=0, editable=False, verbose_name='id_estado'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='usuario',
            field=models.IntegerField(editable=False, null=True, verbose_name='Usuario'),
        ),
    ]
