# Generated by Django 3.2.7 on 2021-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(editable=False, max_length=100, verbose_name='Maquina')),
                ('orden', models.IntegerField(editable=False, verbose_name='Orden')),
                ('noparte', models.IntegerField(editable=False, verbose_name='NumeroParte')),
                ('modelo', models.IntegerField(editable=False, verbose_name='Modelo')),
                ('qty', models.IntegerField(editable=False, verbose_name='Qty')),
                ('fecha', models.DateField(editable=False, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'PlanP',
                'verbose_name_plural': 'PlanP',
            },
        ),
        migrations.CreateModel(
            name='RegProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(editable=False, max_length=100, verbose_name='maquina')),
                ('area', models.CharField(editable=False, max_length=10, verbose_name='área')),
                ('orden', models.IntegerField(editable=False, max_length=100, verbose_name='orden')),
                ('noparte', models.IntegerField(editable=False, max_length=100, verbose_name='noparte')),
                ('qtyprod', models.IntegerField(editable=False, verbose_name='QtyProd')),
                ('active', models.BooleanField(editable=False, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado:')),
                ('usuario', models.IntegerField(editable=False, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Produccion',
                'verbose_name_plural': 'Registros Produccion',
            },
        ),
    ]
