# Generated by Django 3.2.7 on 2021-10-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regprod',
            name='noparte',
            field=models.IntegerField(editable=False, verbose_name='noparte'),
        ),
        migrations.AlterField(
            model_name='regprod',
            name='orden',
            field=models.IntegerField(editable=False, verbose_name='orden'),
        ),
    ]
