# Generated by Django 3.2.7 on 2021-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_material', '0002_auto_20211019_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pp',
            name='noparte',
            field=models.CharField(editable=False, max_length=100, verbose_name='NumeroParte'),
        ),
    ]
