# Generated by Django 3.2.7 on 2021-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_material', '0003_alter_pp_noparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pp',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
