# Generated by Django 3.2.7 on 2021-10-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_material', '0004_pp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regprod',
            name='noparte',
            field=models.CharField(editable=False, max_length=100, verbose_name='noparte'),
        ),
    ]
